name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install

      - name: Build Jupyter book
        run: |
          pipenv run jupyter-book clean atelier
          pipenv run jupyter-book build atelier

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-site
          path: atelier/_build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built site
        uses: actions/download-artifact@v3
        with:
          name: built-site
          path: atelier/_build

      - name: Deploy to GitHub Pages
        run: |
          mv atelier/_build/html public

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public-site
          path: public
